### ISSUE TITLE
Refer to shadow

### ISSUE THREAD

**Issue by Xintao-C** [hub-se/jpf-shadow#2]
A question about run shadow-jpf:
  when I run jpf-shadow with foo(-2), foo(-2) can result in difffalse in line 22, why the output is foo(-88) instead of foo(-2). Can you tell me why ?
thank you.
![图片](https://user-images.githubusercontent.com/43160698/70878619-2ff51800-1ffd-11ea-9277-c3a3e3dc3af6.png)

**Comment by yannicnoller** [comment]
Hi @Xintao-C,

thanks for your interest in our work! The value "-2" is used to drive the exploration. "-88" is the result when solving the path condition with a constraint solver. In this case they both cover the same path, but in our implementation we check all diff paths and report the satisfying values based on the model by the constraint solver.

Best
Yannic
